--- # -------------------------------------
#--------------------------------------
# 菜单配置说明
# identifier ： 唯一标识不可重复
# name       ： 菜单显示名称
# pageref    ： 本站点链接地址，与 URL 选其一
# url        ： 站点外部链接地址，以 https 或者 https 开头
# pre        ： 菜单小图标
# weight     ： 显示顺序，字数越小越靠前
#
# Menus Settings
# identifier : Unique ID cannot be repeated
# name       : Menu name
# pageref    : Link of webiste and not appeare same time with url
# url        : Exteneral link out of website and start with https or https
# pre        : Icon of menu
# weight     : Order number and smaller is top
main:
  - identifier: home
    name: 首頁
    pageref: /
    pre: home
    weight: 1
  - identifier: about
    name: 關於
    pageref: /about.html
    pre: user
    weight: 2
  - identifier: plane
    name: 航空城
    pageref: /categories/桃園航空城/
    pre: plane
    weight: 4
  - identifier: blog
    name: 個人網誌
    pageref: /post
    pre: leaf
    weight: 5
